// plugins/withCertPinning.js
//
// Writes the certificate pins into the native projects at prebuild.
//
// Pinning cannot be done from JavaScript. On Android it is a
// network_security_config.xml referenced from the manifest; on iOS it is
// NSPinnedDomains in Info.plist. Both are native configuration, so they have to
// be injected by a config plugin -- which is what this is.
//
// The pins themselves come from lib/certPins.ts and are NOT duplicated here.
// Two copies of a pin set is how an app ships with the wrong one.

const { withAndroidManifest, withDangerousMod, withInfoPlist } = require("expo/config-plugins")
const fs = require("fs")
const path = require("path")

/**
 * Read the pins out of the TypeScript source.
 *
 * Parsed rather than imported: a config plugin runs in plain Node during
 * prebuild, with no TypeScript loader available. The regexes are anchored to
 * the exact constant names, and the plugin THROWS if it cannot find them --
 * silently shipping an unpinned build is the failure this must not have.
 */
function readPins(projectRoot) {
  const file = path.join(projectRoot, "lib", "certPins.ts")
  const src = fs.readFileSync(file, "utf8")

  const grab = (name) => {
    // String.raw, and that is not pedantry. In an ordinary template literal
    // `\s` is not a recognised escape, so it collapses to a bare "s" before the
    // RegExp constructor ever sees it: the pattern becomes `name:s*['"]`, which
    // needs zero-or-more letter s where the file has a space, and matches
    // nothing. The plugin then threw its own refusal on the build machine and
    // took the APK down. Covered by __tests__/certPinningPlugin.test.ts.
    const m = new RegExp(String.raw`${name}:\s*['"]([^'"]+)['"]`).exec(src)
    if (!m) {
      throw new Error(
        `withCertPinning: could not read "${name}" from lib/certPins.ts. ` +
          `Refusing to build an unpinned app.`,
      )
    }
    return m[1]
  }

  return {
    hostname: grab("hostname"),
    intermediate: grab("intermediate"),
    root: grab("root"),
    expires: grab("expires"),
  }
}

const CONFIG_NAME = "network_security_config"

function androidXml(pins) {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by plugins/withCertPinning.js from lib/certPins.ts. Do not edit. -->
<network-security-config>
  <domain-config cleartextTrafficPermitted="false">
    <domain includeSubdomains="false">${pins.hostname}</domain>
    <pin-set expiration="${pins.expires}">
      <pin digest="SHA-256">${pins.intermediate}</pin>
      <pin digest="SHA-256">${pins.root}</pin>
    </pin-set>
  </domain-config>
  <base-config cleartextTrafficPermitted="false">
    <trust-anchors><certificates src="system" /></trust-anchors>
  </base-config>
</network-security-config>
`
}

const withCertPinning = (config) => {
  // --- Android: write the XML and point the manifest at it ------------------
  config = withDangerousMod(config, [
    "android",
    async (cfg) => {
      const pins = readPins(cfg.modRequest.projectRoot)
      const dir = path.join(
        cfg.modRequest.platformProjectRoot,
        "app", "src", "main", "res", "xml",
      )
      fs.mkdirSync(dir, { recursive: true })
      fs.writeFileSync(path.join(dir, `${CONFIG_NAME}.xml`), androidXml(pins))
      return cfg
    },
  ])

  config = withAndroidManifest(config, (cfg) => {
    const app = cfg.modResults.manifest.application?.[0]
    if (app) {
      app.$["android:networkSecurityConfig"] = `@xml/${CONFIG_NAME}`
      // Belt and braces: the base-config above already forbids it.
      app.$["android:usesCleartextTraffic"] = "false"
    }
    return cfg
  })

  // --- iOS: NSPinnedDomains, iOS 14+ ---------------------------------------
  config = withInfoPlist(config, (cfg) => {
    const pins = readPins(cfg.modRequest.projectRoot)
    cfg.modResults.NSAppTransportSecurity = {
      ...(cfg.modResults.NSAppTransportSecurity || {}),
      NSPinnedDomains: {
        [pins.hostname]: {
          NSIncludesSubdomains: false,
          NSPinnedCAIdentities: [
            { "SPKI-SHA256-BASE64": pins.intermediate },
            { "SPKI-SHA256-BASE64": pins.root },
          ],
        },
      },
    }
    return cfg
  })

  return config
}

module.exports = withCertPinning

// Exported so the parsing can be tested without running a prebuild. The bug
// this guards against was invisible to `expo config`, which does not run
// dangerous mods -- only a real prebuild or a direct call reaches this code.
module.exports.readPins = readPins
module.exports.androidXml = androidXml
